version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/eFormDashboard.Pn"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microting.eFormApi.BasePn
    versions:
    - 2.0.100
    - 2.0.101
    - 2.0.102
    - 2.0.103
    - 2.0.104
    - 2.0.106
    - 2.0.108
    - 2.0.112
    - 2.0.122
    - 2.0.126
    - 2.0.127
    - 2.0.128
    - 2.0.84
    - 2.0.87
    - 2.0.88
    - 2.0.89
    - 2.0.90
    - 2.0.91
    - 2.0.93
    - 2.0.94
    - 2.0.95
    - 2.0.97
    - 2.0.98
    - 2.1.0
    - 2.1.2
  - dependency-name: Microting.eForm
    versions:
    - 4.3.11
    - 4.3.12
    - 4.3.14
    - 4.3.15
    - 4.3.16
    - 4.3.17
    - 4.3.18
    - 4.3.4
    - 4.3.8
    - 4.3.9
    - 4.4.1
    - 4.4.11
    - 4.4.14
    - 4.4.2
    - 4.4.22
    - 4.4.31
    - 4.4.35
    - 4.4.36
    - 4.4.37
    - 4.4.4
    - 4.4.6
    - 4.4.7
    - 4.4.9
    - 4.5.0
    - 4.5.2
  - dependency-name: Microting.eFormDashboardBase
    versions:
    - 2.0.32
    - 2.0.35
    - 2.0.36
    - 2.0.38
    - 2.0.39
    - 2.0.41
    - 2.0.42
    - 2.0.43
    - 2.0.44
    - 2.0.47
    - 2.0.49
    - 2.0.54
    - 2.0.55
    - 2.0.62
    - 2.0.63
    - 2.0.64
    - 2.0.65
    - 2.1.0
    - 2.1.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: NUnit
    versions:
    - 3.13.0
